---
galaxy_info:
  author: Sergey Alimov (sm0ke87)
  description: Suricata ansible role
  company: NBFC «Mobile card» Limited.
  license: license (GPL-2.0-or-later, MIT, etc)
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      version:
        - 20.04
#dependencies:
#  - role: ans-role-suricata
  